name: ALL
on:
  pull_request:
  #push:
  #schedule:
    #- cron: '0 * * * *'      # Every HOUR
    #- cron: '0 */3 * * *'   # Every 2 hours
    #- cron: '0 */5 * * *'   # Every 5 hours
    #- cron: '0 0 * * *'     # Every day
jobs:
 WebSocket:
   runs-on: ubuntu-latest    
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v4
       with:
        ref: websocket_tests
       
     - name: Run Cypress Test
       uses: cypress-io/github-action@v6
       with:         
         browser: chrome
         #spec: "cypress/e2e/1_login.cy.js"

     #- name: REPORT
       #uses: actions/upload-artifact@v4
       #if: failure()
       #with:
        #name: Report
        #path: ~/cypress/reports
          
     - name: "Telegram notification on FAILURE"
       if: failure()
       uses: "appleboy/telegram-action@master"
       with: 
        to: ${{secrets.TELEGRAM_CHAT_ID}}
        token: ${{secrets.TELEGRAM_TOKEN}}
        message: |
          ОСНОВНОЙ ТЕСТ завершился неудачей!
          Запуск теста по ${{github.event_name}}
        #photo: /home/runner/work/FLV/FLV/cypress/screenshots/**/*.png
        video: /home/runner/work/FLV/FLV/cypress/video/*.mp4
        document: /home/runner/work/FLV/FLV/cypress/reports/html/*.html

 UI_TESTS:
          if: ${{always()}}
          needs: WebSocket
          runs-on: ubuntu-latest    
          steps:
            - name: Checkout GitCode
              uses: actions/checkout@v4
              with:
               ref: ui_tests
              
            - name: Run Cypress Test
              uses: cypress-io/github-action@v6
              with:         
                browser: chrome
                #spec: "cypress/e2e/1_login.cy.js"
       
            #- name: REPORT
              #uses: actions/upload-artifact@v4
              #if: failure()
              #with:
               #name: Report
               #path: ~/cypress/reports
       
            #- name: "Telegram notification" 
              #uses: "appleboy/telegram-action@master"
              #with: 
               #to: ${{secrets.TELEGRAM_CHAT_ID}}
               #token: ${{secrets.TELEGRAM_TOKEN}}
               #message: |
                 #SUCCES!!!
                 #Запуск теста по ${{github.event_name}} 
                 #Ветка - ${{github.ref_name}}
                 
            - name: "Telegram notification on FAILURE"
              if: failure()
              uses: "appleboy/telegram-action@master"
              with: 
               to: ${{secrets.TELEGRAM_CHAT_ID}}
               token: ${{secrets.TELEGRAM_TOKEN}}
               message: |
                 UI-ТЕСТЫ завершились неудачей!
                 Запуск теста по ${{github.event_name}}
               #photo: /home/runner/work/FLV/FLV/cypress/screenshots/**/*.png
               video: /home/runner/work/FLV/FLV/cypress/video/*.mp4
               document: /home/runner/work/FLV/FLV/cypress/reports/html/*.html
               
 PROFILE_TESTS:
                if: ${{always()}}
                needs: [WebSocket, UI_TESTS]
                runs-on: ubuntu-latest    
                steps:
                  - name: Checkout GitCode
                    uses: actions/checkout@v4
                    with:
                     ref: profile_tests
                    
                  - name: Run Cypress Test
                    uses: cypress-io/github-action@v6
                    with:         
                      browser: chrome
                       
                  - name: "Telegram notification on FAILURE"
                    if: failure()
                    uses: "appleboy/telegram-action@master"
                    with: 
                     to: secrets.TELEGRAM_CHAT_ID
                     token: secrets.TELEGRAM_TOKEN
                     message: |
                       ТЕСТЫ ЛК завершился неудачей!
                       Запуск теста по github.event_name
                     #photo: /home/runner/work/FLV/FLV/cypress/screenshots/**/*.png
                     video: /home/runner/work/FLV/FLV/cypress/video/*.mp4
                     document: /home/runner/work/FLV/FLV/cypress/reports/html/*.html
        
        